#!/bin/bash
######################################
######################################
##	Desenvolvido por :				##
##	 	Edgar Meneghetti			##
##		Alessandro Librelato 		##
##		Roberto Fettuccia			##
##									##
##  OS : DEBIAN Whezzy				##
##	Data : 12/03/2014				##
##	Versao : 2.0					##
##									##
##	Dependencias :					##
##		mysql-client				##
##		gammu						##
##		postfix						##
######################################
######################################
#set -x
#####################################
## Definicao das variaveis globais ##
#####################################

Loop=1
contagemErro=0
logFile=/var/log/sendvoucher.log ## Arquivo de log
gammuConfig=/etc/gammu.conf ## Configuracao do Gammu
emailReport="alessandro.librelato@terc.al.rs.gov.br" ## Configuracao de e-mail
maxErrorCount=24   ## Maximo de erros para o modem e SIM desativado - envio de alerta via email. default 24 (+/- 3 minutos)
maxErrorCountSim=3 ## Maximo de erro para o cartao SIM sem creditos
intervalNextTry=5 ## Tempo seg para aguardar cada tentativa/sucesso. default [5]
servidor=$(hostname) ## Nome do servidor

##################################
## Definicoes do banco de dados ##
##################################

servidorBanco="172.30.1.15"
usuarioBanco="smsuser"
senhaUsuarioBanco="sgrela"
dataBase="smsGateway_Halia"

######################################
## Funcao para fazer a QUERY no SQL ##
######################################

function query()
	{
	# recebe sql string de fora da function
	QUERY_SQL=${1} 
	# executa o SQL (SED -n 2p retira cabecalho da tabela)
	echo $(echo ${QUERY_SQL} | mysql --host=${servidorBanco} --user=${usuarioBanco} --password=${senhaUsuarioBanco} ${dataBase} | sed -n "2p")
	}

############
## Inicio ##
############

## Enquanto loop for = 1 e contagemErro diferente de maxErrorCount, executa ##
while [ ${Loop} == 1 ] && [ ! ${contagemErro} == ${maxErrorCount} ]; do
	## Faz consulta SQL para verificar qual campo voucher esta preenchido, campo telefone e emissao estao vaziu e atribui a variavel consultaSQL ##
	consultaSQL=$(echo $(query "SELECT voucher,telefone FROM dados WHERE telefone!='' AND emissao='2' LIMIT 1;"))
	## Retira o numero do voucher da cunsulta SQL ##
	voucherSQL=$(echo "$consultaSQL" | cut -d " " -f 1 | sed "s/ //g" )
	## Retira o numero do telefone da cunsulta SQL ##
	telefoneSQL=$(echo "$consultaSQL" | cut -d " " -f 2 | sed "s/ //g" )
	
	## Se voucher diferente de vazio E telefone diferente de vazio envia o sms e grava no log a acao ##
	if [ ! -z ${voucherSQL} ] && [ ! -z ${telefoneSQL} ]; then
		horaEnvio="$(date)"
		filtroExecucao="$(echo 'Assembleia Legislativa RS    Codigo acesso: '${voucherSQL} |gammu -c ${gammuConfig} --sendsms TEXT ${telefoneSQL})"
		## Se a variavel filtroExecucao tem a mensagem OK, faz update no banco dados com o telefone e a hora de envio usando a funcao query. ##
		if [[ $filtroExecucao = *"OK"* ]]; then
			query "UPDATE dados SET emissao='${horaEnvio}' WHERE voucher='${voucherSQL}' AND telefone='${telefoneSQL}';"
			printf "${horaEnvio} ${telefoneSQL} ${filtroExecucao} \n" >> ${logFile}
			contagemErro=0
		## Se a variavel filtroExecucao nao tem a mensagem OK, entra no tratamento do erro ##
		
		elif [[ $filtroExecucao = *"500"* ]]; then
			contagemErro=$((contagemErro+1))
			sleep ${intervalNextTry}
			## se Contagem de erro >= maxErrorCountSim Notifica Por Email e mata o processo do script ##
			if [ ${contagemErro} -ge ${maxErrorCountSim} ]; then
				printf "${horaEnvio} ${filtroExecucao} \n" >> ${logFile}
				echo "Data/Hora : $(date) --- MSG : "${filtroExecucao} -- SIM sem credito | mail -s "${servidor} - smsGataway (ERRO)" ${emailReport}
				query "UPDATE dados SET controle='x' WHERE voucher='${voucherSQL}' AND telefone='${telefoneSQL}';"
			fi
		else
			contagemErro=$((contagemErro+1))
			sleep ${intervalNextTry}
			## se Contagem de erro >= maxErrorCount Notifica Por Email e mata o processo do script ##
			if [ ${contagemErro} -ge ${maxErrorCount} ]; then
				printf "${horaEnvio} ${filtroExecucao} \n" >> ${logFile}
				echo "Data/Hora : $(date) --- MSG : "${filtroExecucao} | mail -s "${servidor} - smsGataway (ERRO)" ${emailReport}
				query "UPDATE dados SET controle='x' WHERE voucher='${voucherSQL}' AND telefone='${telefoneSQL}';"
			fi
		fi
	else
		## sai do loop ##
		Loop=0
	fi
done